[target.thumbv7em-none-eabihf]
runner = "probe-run --chip STM32G431CBUx"
# runner = "arm-none-eabi-gdb -q"

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"